### ISSUE TITLE
Breath of the Kami

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1901]
- [x] Hisu Mori Toride #1887 
- [x] Sacred Sanctuary #1977 
- [x] Demonstrating Excellence #1888 
- [x] Third Tower Guard #2021 
- [x] Hiruma Outpost #2022
- [x] Fu Sui Disciple #1892
- [x] Matsu Seventh Legion #1933 
- [x] Isawa Uona #1893 
- [x] Soshi Shadowshaper #2023
- [x] Heartless Intimidator #2024
- [x] Shinjo Shono #1894 
- [x] Shiotome Encampment #1895 
- [x] Kudaka #1896 
- [x] Formal Invitiation #2025
- [x] The Mirror's Gaze #1897
- [x] Ancient Master #2026
- [x] Hurricane Punch #1898 
- [x] Even the Odds #1934 
- [x] Winds of Change #1899 
- [x] Maze of Illusion #1900

**Comment by NoahTheDuke** [comment]
Nice done, everyone!!!
