### ISSUE TITLE
Tainted Lands

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1922]
- [ ] Teachings of the Elements #1913 
- [ ] Unknown
- [ ] Upholding Authority #1914 
- [ ] Apprentice Earthcaller #1915 
- [ ] Kuni Yori #1916 
- [ ] Unknown
- [ ] Unknown
- [ ] Unknown
- [ ] Unknown
- [ ] Sneaky Shinjo #1917 
- [ ] Marauding Oni #1918 
- [ ] Spreading the Darkness #1919 
- [ ] Unknown
- [ ] Unknown
- [ ] Unknown
- [ ] Feral Ningyo #1920 
- [ ] Oracle of Stone #1921 
- [ ] Unknown
- [ ] Unknown
- [ ] Unknown
