### ISSUE TITLE
The Fires Within

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1992]
- [x] Abandoning Honor #1981 
- [x] Hiruma Kogoe #1982 
- [x] Sadane Student #2197 
- [x] Master Alchemist #1983 
- [x] Wrath of the Kami #1984 
- [x] Ikoma Ikehata #2199
- [x] Ancestral Armory #2200 
- [x] Chikai Order Protector #2201 
- [x] Soshi Shiori #2202 
- [x] Battle Maiden Recruit #1985 
- [x] Wicked Tetsubo #1986 
- [x] Icon of Favor #1987 
- [x] Insult to Injury #2206 
- [x] Smoke #1988 
- [x] Jurojin's Curse #2203 
- [x] Infiltrator #1989 
- [x] Shiksha Scout #1990 
- [x] Invocation of Ash #1991 
- [x] Mantis Seafarer #2204 
- [x] Breach of Etiquette #2205
