### ISSUE TITLE
The Ebb and Flow (12 of 20 spoiled)

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2005]
- [ ] Unknown
- [ ] Unknown
- [ ] Ikebana Artisan #1993
- [ ] Volcanic Troll #1994
- [ ] Unknown
- [ ] Unknown
- [ ] Disguised Protector #1995
- [ ] Unknown
- [ ] Master of the Swift Waves #1996
- [ ] Unknown
- [ ] Nezumi Infiltrator #1997
- [ ] Unknown
- [ ] Menacing Iron Warrior #1998
- [ ] Soul Beyond Reproach #1999
- [ ] Hawk Tattoo #2000 
- [ ] Heroic Resolve #2001 
- [ ] Unknown
- [ ] Ofushikai #2002 
- [ ] Deceptive Offer #2003 
- [ ] Force of the River #2004
