### ISSUE TITLE
Elements Unbound (10 of 20 spoiled)

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2251]
- [ ] Unknown
- [ ] Unknown
- [ ] Web of Lies #2241
- [ ] Unknown
- [ ] Tengu Sensei #2242 
- [ ] Agasha Shunsen
- [ ] Unknown
- [ ] Reader of Omens
- [ ] Reclusive Zokujin #2243 
- [ ] Minami Kaze Regulars #2244 
- [ ] Mantis Tenjinka #2245 
- [ ] Awakened Tsukumogami #2246 
- [ ] Unknown
- [ ] Specialized Defenses #2247 
- [ ] Unknown
- [ ] Unknown
- [ ] Unknown
- [ ] Roving Michibiku #2248 
- [ ] Taryu Jiai #2249 
- [ ] Unleash the Djinn #2250
