### ISSUE TITLE
Underhand of the Emperor Pack (28/28)

### ISSUE THREAD

**Issue by CDMayberry** [gryffon/ringteki#2479]
(In no particular order)

- [x] Kyuden Bayushi #2478
- [x] Support of the Scorpion #2482
- [x] Court of Deception #2477
- [x] Akodo Kage #2476
- [x] Bayushi Aramoro #2475
- [x] Stolen Breath #2474
- [x] Seppun Truthseeker #2473
- [x] Opium Wastrel #2472
- [x] Brother's Gift Dojo #2471
- [x] Shosuro Takao #2470
- [x] From the Shadows #2469
- [x] Alibi Artist #2468
- [x] Liar's Mask #2467
- [x] Asako Maezawa #2466
- [x] Utaku Tetsko #2465
- [x] Offer Testimony #2464
- [x] Peasant's Advice #2463
- [x] Soshi Aoi #2462
- [x] Insolent Rival #2461
- [x] Bayushi's Whisperer #2460
- [x] Ignoble Enforcers #2459 
- [x] Duty #2481
- [x] Doji Fumiki #2480
- [x] Kitsuki Shomon #2485 
- [x] Yasuki Oguri #2486
- [x] Bayushi Collector #2501 
- [x] Make an Opening #2502 
- [x] Stolen Secrets #2503
