### ISSUE TITLE
Children of the Empire (fully spoiled)

### ISSUE THREAD

**Issue by jamesoddy** [gryffon/ringteki#2618]
### Implementations/Tests should be pulled into the [cote ](https://github.com/gryffon/ringteki/tree/cote) branch ###

- [x] #2600 Student of War
- [x] #2601 Social Puppeteer
- [x] #2602 Courtly Challenger
- [x] #2603 Honest Challenger
- [x] #2604 Mirumoto Daisho
- [x] #2605 In Defense of Rokugan
- [x] #2606 Subdue the Spirits
- [x] #2607 Akodo Toturi
- [x] #2608 Jewel of the Khamasin
- [x] #2609 Hand to Hand
- [x] #2610 Karmic Balance
- [x] #2611 Try Again Tomorrow
- [x] #2612 Sage of Gisei Toshi
- [x] #2613 Heavy Ballista
- [x] #2614 Miyako's Undertaking
- [x] #2664 Magnificent Triumph
- [x] #2706 Honorable Challenger
- [x] #2707 Tranquil Philosopher
- [x] #2708 Infiltrator's Tools
- [x] #2709 Shiotome Heroine
- [x] #2710 Sincere Challenger
- [x] #2722 Challenge on the Fields
- [x] #2721 Ide Negotiator
- [x] #2720 Utaku Kamoko
- [x] #2719 Isawa Ujina
- [x] #2718 Unmatched Expertise
- [x] #2717 Gift of Amaterasu
- [x] #2716 Glorious Victory
- [x] #2715 Matsu Tsuko
- [x] #2714 Ikoma Orator
- [x] #2713 Kiku Matsuri
- [x] #2731 Honed Nodachi
- [x] #2736 Loyal Challenger
- [x] #2737 Daring Challenger
- [x] #2732 Midnight Revels
- [x] #2733 Yasuki Procurer
- [x] #2734 Shosuro Hametsu
- [x] #2735 Kirei-ko
- [x] #2749 Fire Tensai Acolyte
- [x] #2748 True Strike Kenjutsu
- [x] #2747 Smuggling Deal
- [x] #2750 Warm Welcome
- [x] #2615 Mirumoto Hitomi
- [x] #2616 Aspiring Challenger
- [x] #2617 Hida Yakamo - needs double checking when properly released
- [x] #2619 The Fires of Justice - needs double checking when properly released
- [x] #2777 Stay Your Hand
- [x] #2784 Kakita Toshimoko
- [x] #2785 Kakita Dôjô
- [x] #2786 Iaijutsu Master
- [x] #2787 Prudent Challenger
- [x] #2788 Mirumoto Dôjô
- [x] #2789 Illustrious Forge
- [x] #2791 Seppun Hidden Guard
- [x] #2792 Miya Library
- [x] #2793 Temple of the Dragons
- [x] #2794 Storied Defeat
- [x] #2801 Hantei XXXVIII
- [x] #2802 Humble Magistrate
- [x] #2803 Righteous Magistrate
- [x] #2804 Unveiled Destiny
- [x] #2805 Defend Your Honor
- [x] Siege Captain - no scripting required
- [x] Attendant to the Emperor - no scripting required
- [x] #2837 Vassal Fields
- [x] #2838 Ishigenkin Soloist
- [x] #2839 Paragon of Grace
- [x] #2840 Kitsuki Counsellor
- [x] #2841 Tactician's Camp
- [x] #2842 Ancestral Shrine
- [x] #2843 Midnight Prowler
- [x] #2844 Outskirts Sentry
- [x] #2845 Proving Ground
- [x] #2846 Guardian of Virtue
- [x] #2847 Civil Discourse
- [x] #2848 Solitary Strength
- [x] #2849 Severed from the Stream
- [x] #2850 Unmask
- [x] #2851 Shinjo Ambusher
- [x] #2852 Leniency
- [x] #2853 Kujira's Hireling
- [x] #2854 Prayers to Ebisu
